// GENERATED by scripts/gen-db-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      appointment_natures: {
        Row: {
          code: string;
          name: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      attendance_corrections: {
        Row: {
          id: string;
          request_no: string;
          employee_id: string;
          work_date: string;
          correction_type: string;
          proposed_time_in: string | null;
          proposed_time_out: string | null;
          reason: string | null;
          remarks: string | null;
          status: string;
          workflow_code: string | null;
          current_step_order: number | null;
          submitted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_no?: string;
          employee_id: string;
          work_date: string;
          correction_type: string;
          proposed_time_in?: string | null;
          proposed_time_out?: string | null;
          reason?: string | null;
          remarks?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_no?: string;
          employee_id?: string;
          work_date?: string;
          correction_type?: string;
          proposed_time_in?: string | null;
          proposed_time_out?: string | null;
          reason?: string | null;
          remarks?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      attendance_records: {
        Row: {
          id: string;
          employee_id: string;
          work_date: string;
          time_in: string | null;
          time_out: string | null;
          break_minutes: number;
          total_minutes: number | null;
          status_code: string;
          remarks: string | null;
          source: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          work_date: string;
          time_in?: string | null;
          time_out?: string | null;
          break_minutes?: number;
          status_code: string;
          remarks?: string | null;
          source?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          work_date?: string;
          time_in?: string | null;
          time_out?: string | null;
          break_minutes?: number;
          status_code?: string;
          remarks?: string | null;
          source?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      attendance_statuses: {
        Row: {
          code: string;
          name: string;
          counts_as_present: boolean;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          counts_as_present?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          counts_as_present?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: number;
          occurred_at: string;
          actor_user_id: string | null;
          actor_label: string;
          action: string;
          module: string;
          entity_type: string | null;
          entity_id: string | null;
          subject_employee_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          reason: string | null;
          metadata: Json;
        };
        Insert: {
          id?: number;
          occurred_at?: string;
          actor_user_id?: string | null;
          actor_label: string;
          action: string;
          module: string;
          entity_type?: string | null;
          entity_id?: string | null;
          subject_employee_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          reason?: string | null;
          metadata?: Json;
        };
        Update: {
          id?: number;
          occurred_at?: string;
          actor_user_id?: string | null;
          actor_label?: string;
          action?: string;
          module?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          subject_employee_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          reason?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
      document_categories: {
        Row: {
          code: string;
          name: string;
          group_name: string;
          is_required: boolean;
          requires_expiry: boolean;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          group_name: string;
          is_required?: boolean;
          requires_expiry?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          group_name?: string;
          is_required?: boolean;
          requires_expiry?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      document_versions: {
        Row: {
          id: string;
          document_id: string;
          version_no: number;
          storage_path: string;
          file_name: string;
          mime_type: string;
          size_bytes: number;
          sha256: string;
          uploaded_by: string;
          uploaded_by_name: string;
          uploaded_at: string;
          change_reason: string | null;
        };
        Insert: {
          id?: string;
          document_id: string;
          version_no: number;
          storage_path: string;
          file_name: string;
          mime_type: string;
          size_bytes: number;
          sha256: string;
          uploaded_by?: string;
          uploaded_by_name: string;
          uploaded_at?: string;
          change_reason?: string | null;
        };
        Update: {
          id?: string;
          document_id?: string;
          version_no?: number;
          storage_path?: string;
          file_name?: string;
          mime_type?: string;
          size_bytes?: number;
          sha256?: string;
          uploaded_by?: string;
          uploaded_by_name?: string;
          uploaded_at?: string;
          change_reason?: string | null;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          doc_no: string;
          employee_id: string;
          category_code: string;
          title: string;
          doc_date: string | null;
          issuing_agency: string | null;
          expires_on: string | null;
          status: string;
          remarks: string | null;
          current_version_no: number;
          related_entity_type: string | null;
          related_entity_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          deleted_reason: string | null;
        };
        Insert: {
          id?: string;
          doc_no?: string;
          employee_id: string;
          category_code: string;
          title: string;
          doc_date?: string | null;
          issuing_agency?: string | null;
          expires_on?: string | null;
          status?: string;
          remarks?: string | null;
          current_version_no?: number;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          deleted_reason?: string | null;
        };
        Update: {
          id?: string;
          doc_no?: string;
          employee_id?: string;
          category_code?: string;
          title?: string;
          doc_date?: string | null;
          issuing_agency?: string | null;
          expires_on?: string | null;
          status?: string;
          remarks?: string | null;
          current_version_no?: number;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          deleted_reason?: string | null;
        };
        Relationships: [];
      };
      employee_addresses: {
        Row: {
          id: string;
          employee_id: string;
          address_type: string;
          house_no: string | null;
          street: string | null;
          subdivision: string | null;
          barangay: string | null;
          city_municipality: string | null;
          province: string | null;
          zip_code: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          address_type: string;
          house_no?: string | null;
          street?: string | null;
          subdivision?: string | null;
          barangay?: string | null;
          city_municipality?: string | null;
          province?: string | null;
          zip_code?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          address_type?: string;
          house_no?: string | null;
          street?: string | null;
          subdivision?: string | null;
          barangay?: string | null;
          city_municipality?: string | null;
          province?: string | null;
          zip_code?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_education: {
        Row: {
          id: string;
          employee_id: string;
          level: string;
          school: string;
          degree_course: string | null;
          period_from: number | null;
          period_to: number | null;
          highest_level_units: string | null;
          year_graduated: number | null;
          honors: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          level: string;
          school: string;
          degree_course?: string | null;
          period_from?: number | null;
          period_to?: number | null;
          highest_level_units?: string | null;
          year_graduated?: number | null;
          honors?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          level?: string;
          school?: string;
          degree_course?: string | null;
          period_from?: number | null;
          period_to?: number | null;
          highest_level_units?: string | null;
          year_graduated?: number | null;
          honors?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_eligibility: {
        Row: {
          id: string;
          employee_id: string;
          eligibility: string;
          rating: number | null;
          exam_date: string | null;
          exam_place: string | null;
          license_number: string | null;
          license_validity: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          eligibility: string;
          rating?: number | null;
          exam_date?: string | null;
          exam_place?: string | null;
          license_number?: string | null;
          license_validity?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          eligibility?: string;
          rating?: number | null;
          exam_date?: string | null;
          exam_place?: string | null;
          license_number?: string | null;
          license_validity?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_family: {
        Row: {
          id: string;
          employee_id: string;
          relation: string;
          last_name: string;
          first_name: string;
          middle_name: string | null;
          extension_name: string | null;
          birth_date: string | null;
          occupation: string | null;
          employer: string | null;
          business_address: string | null;
          telephone: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          relation: string;
          last_name: string;
          first_name: string;
          middle_name?: string | null;
          extension_name?: string | null;
          birth_date?: string | null;
          occupation?: string | null;
          employer?: string | null;
          business_address?: string | null;
          telephone?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          relation?: string;
          last_name?: string;
          first_name?: string;
          middle_name?: string | null;
          extension_name?: string | null;
          birth_date?: string | null;
          occupation?: string | null;
          employer?: string | null;
          business_address?: string | null;
          telephone?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_gov_ids: {
        Row: {
          id: string;
          employee_id: string;
          id_type: string;
          id_number: string;
          issued_at: string | null;
          issued_on: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          id_type: string;
          id_number: string;
          issued_at?: string | null;
          issued_on?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          id_type?: string;
          id_number?: string;
          issued_at?: string | null;
          issued_on?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_other_info: {
        Row: {
          id: string;
          employee_id: string;
          category: string;
          description: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          category: string;
          description: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          category?: string;
          description?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_private: {
        Row: {
          employee_id: string;
          birth_date: string | null;
          birth_place: string | null;
          civil_status: string | null;
          citizenship: string | null;
          blood_type: string | null;
          tin: string | null;
          gsis_bp_no: string | null;
          philhealth_no: string | null;
          pagibig_no: string | null;
          personal_email: string | null;
          mobile_no: string | null;
          updated_at: string;
        };
        Insert: {
          employee_id: string;
          birth_date?: string | null;
          birth_place?: string | null;
          civil_status?: string | null;
          citizenship?: string | null;
          blood_type?: string | null;
          tin?: string | null;
          gsis_bp_no?: string | null;
          philhealth_no?: string | null;
          pagibig_no?: string | null;
          personal_email?: string | null;
          mobile_no?: string | null;
          updated_at?: string;
        };
        Update: {
          employee_id?: string;
          birth_date?: string | null;
          birth_place?: string | null;
          civil_status?: string | null;
          citizenship?: string | null;
          blood_type?: string | null;
          tin?: string | null;
          gsis_bp_no?: string | null;
          philhealth_no?: string | null;
          pagibig_no?: string | null;
          personal_email?: string | null;
          mobile_no?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_references: {
        Row: {
          id: string;
          employee_id: string;
          name: string;
          address: string | null;
          telephone: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          name: string;
          address?: string | null;
          telephone?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          name?: string;
          address?: string | null;
          telephone?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_training: {
        Row: {
          id: string;
          employee_id: string;
          title: string;
          date_from: string | null;
          date_to: string | null;
          hours: number | null;
          training_type: string | null;
          conducted_by: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          title: string;
          date_from?: string | null;
          date_to?: string | null;
          hours?: number | null;
          training_type?: string | null;
          conducted_by?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          title?: string;
          date_from?: string | null;
          date_to?: string | null;
          hours?: number | null;
          training_type?: string | null;
          conducted_by?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_voluntary_work: {
        Row: {
          id: string;
          employee_id: string;
          organization: string;
          date_from: string | null;
          date_to: string | null;
          hours: number | null;
          nature_of_work: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          organization: string;
          date_from?: string | null;
          date_to?: string | null;
          hours?: number | null;
          nature_of_work?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          organization?: string;
          date_from?: string | null;
          date_to?: string | null;
          hours?: number | null;
          nature_of_work?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_work_experience: {
        Row: {
          id: string;
          employee_id: string;
          date_from: string;
          date_to: string | null;
          position_title: string;
          agency: string;
          monthly_salary: number | null;
          salary_grade_step: string | null;
          appointment_status: string | null;
          is_government: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          date_from: string;
          date_to?: string | null;
          position_title: string;
          agency: string;
          monthly_salary?: number | null;
          salary_grade_step?: string | null;
          appointment_status?: string | null;
          is_government?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          date_from?: string;
          date_to?: string | null;
          position_title?: string;
          agency?: string;
          monthly_salary?: number | null;
          salary_grade_step?: string | null;
          appointment_status?: string | null;
          is_government?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employees: {
        Row: {
          id: string;
          employee_no: string;
          prc_employee_no: string | null;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          extension_name: string | null;
          sex: string | null;
          official_email: string | null;
          position_id: string | null;
          plantilla_item_id: string | null;
          position_number: string | null;
          salary_grade: number | null;
          salary_step: number | null;
          employment_status_code: string | null;
          appointment_nature_code: string | null;
          original_appointment_date: string | null;
          current_appointment_date: string | null;
          date_assumed: string | null;
          org_unit_id: string | null;
          supervisor_employee_id: string | null;
          record_status: string;
          separation_date: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_no?: string;
          prc_employee_no?: string | null;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          extension_name?: string | null;
          sex?: string | null;
          official_email?: string | null;
          position_id?: string | null;
          plantilla_item_id?: string | null;
          position_number?: string | null;
          salary_grade?: number | null;
          salary_step?: number | null;
          employment_status_code?: string | null;
          appointment_nature_code?: string | null;
          original_appointment_date?: string | null;
          current_appointment_date?: string | null;
          date_assumed?: string | null;
          org_unit_id?: string | null;
          supervisor_employee_id?: string | null;
          record_status?: string;
          separation_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_no?: string;
          prc_employee_no?: string | null;
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          extension_name?: string | null;
          sex?: string | null;
          official_email?: string | null;
          position_id?: string | null;
          plantilla_item_id?: string | null;
          position_number?: string | null;
          salary_grade?: number | null;
          salary_step?: number | null;
          employment_status_code?: string | null;
          appointment_nature_code?: string | null;
          original_appointment_date?: string | null;
          current_appointment_date?: string | null;
          date_assumed?: string | null;
          org_unit_id?: string | null;
          supervisor_employee_id?: string | null;
          record_status?: string;
          separation_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employment_statuses: {
        Row: {
          code: string;
          name: string;
          description: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      holidays: {
        Row: {
          holiday_date: string;
          name: string;
          kind: string;
        };
        Insert: {
          holiday_date: string;
          name: string;
          kind?: string;
        };
        Update: {
          holiday_date?: string;
          name?: string;
          kind?: string;
        };
        Relationships: [];
      };
      hr_request_types: {
        Row: {
          code: string;
          name: string;
          description: string | null;
          workflow_code: string | null;
          requires_attachment: boolean;
          produces_document: boolean;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          description?: string | null;
          workflow_code?: string | null;
          requires_attachment?: boolean;
          produces_document?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          description?: string | null;
          workflow_code?: string | null;
          requires_attachment?: boolean;
          produces_document?: boolean;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      hr_requests: {
        Row: {
          id: string;
          request_no: string;
          employee_id: string;
          request_type_code: string;
          priority: string;
          subject: string;
          details: string | null;
          assigned_to: string | null;
          result_document_id: string | null;
          status: string;
          workflow_code: string | null;
          current_step_order: number | null;
          submitted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_no?: string;
          employee_id: string;
          request_type_code: string;
          priority?: string;
          subject: string;
          details?: string | null;
          assigned_to?: string | null;
          result_document_id?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_no?: string;
          employee_id?: string;
          request_type_code?: string;
          priority?: string;
          subject?: string;
          details?: string | null;
          assigned_to?: string | null;
          result_document_id?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      import_batches: {
        Row: {
          id: string;
          kind: string;
          file_name: string;
          status: string;
          mapping: Json;
          total_rows: number;
          valid_rows: number;
          error_rows: number;
          imported_rows: number;
          created_by: string | null;
          created_at: string;
          committed_at: string | null;
        };
        Insert: {
          id?: string;
          kind: string;
          file_name: string;
          status?: string;
          mapping?: Json;
          total_rows?: number;
          valid_rows?: number;
          error_rows?: number;
          imported_rows?: number;
          created_by?: string | null;
          created_at?: string;
          committed_at?: string | null;
        };
        Update: {
          id?: string;
          kind?: string;
          file_name?: string;
          status?: string;
          mapping?: Json;
          total_rows?: number;
          valid_rows?: number;
          error_rows?: number;
          imported_rows?: number;
          created_by?: string | null;
          created_at?: string;
          committed_at?: string | null;
        };
        Relationships: [];
      };
      import_rows: {
        Row: {
          id: number;
          batch_id: string;
          row_no: number;
          raw: Json;
          normalized: Json | null;
          errors: Json;
          status: string;
          result: string | null;
        };
        Insert: {
          id?: number;
          batch_id: string;
          row_no: number;
          raw: Json;
          normalized?: Json | null;
          errors?: Json;
          status?: string;
          result?: string | null;
        };
        Update: {
          id?: number;
          batch_id?: string;
          row_no?: number;
          raw?: Json;
          normalized?: Json | null;
          errors?: Json;
          status?: string;
          result?: string | null;
        };
        Relationships: [];
      };
      leave_applications: {
        Row: {
          id: string;
          request_no: string;
          employee_id: string;
          leave_type_code: string;
          date_from: string;
          date_to: string;
          days: number | null;
          reason: string | null;
          status: string;
          workflow_code: string | null;
          current_step_order: number | null;
          submitted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_no?: string;
          employee_id: string;
          leave_type_code: string;
          date_from: string;
          date_to: string;
          days?: number | null;
          reason?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_no?: string;
          employee_id?: string;
          leave_type_code?: string;
          date_from?: string;
          date_to?: string;
          days?: number | null;
          reason?: string | null;
          status?: string;
          workflow_code?: string | null;
          current_step_order?: number | null;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leave_balances: {
        Row: {
          employee_id: string;
          leave_type_code: string;
          year: number;
          beginning: number;
          earned: number;
          used: number;
          updated_at: string;
        };
        Insert: {
          employee_id: string;
          leave_type_code: string;
          year: number;
          beginning?: number;
          earned?: number;
          used?: number;
          updated_at?: string;
        };
        Update: {
          employee_id?: string;
          leave_type_code?: string;
          year?: number;
          beginning?: number;
          earned?: number;
          used?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      leave_types: {
        Row: {
          code: string;
          name: string;
          requires_balance: boolean;
          deducts_balance: boolean;
          accrual_rule: Json | null;
          workflow_code: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          requires_balance?: boolean;
          deducts_balance?: boolean;
          accrual_rule?: Json | null;
          workflow_code?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          requires_balance?: boolean;
          deducts_balance?: boolean;
          accrual_rule?: Json | null;
          workflow_code?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      notification_outbox: {
        Row: {
          id: string;
          notification_id: string;
          channel: string;
          status: string;
          attempts: number;
          last_error: string | null;
          created_at: string;
          sent_at: string | null;
        };
        Insert: {
          id?: string;
          notification_id: string;
          channel: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Update: {
          id?: string;
          notification_id?: string;
          channel?: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          link: string | null;
          entity_type: string | null;
          entity_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string | null;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      number_counters: {
        Row: {
          prefix: string;
          year: number;
          last_value: number;
        };
        Insert: {
          prefix: string;
          year: number;
          last_value?: number;
        };
        Update: {
          prefix?: string;
          year?: number;
          last_value?: number;
        };
        Relationships: [];
      };
      org_unit_types: {
        Row: {
          code: string;
          name: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      org_units: {
        Row: {
          id: string;
          parent_id: string | null;
          unit_type: string;
          code: string;
          name: string;
          head_employee_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parent_id?: string | null;
          unit_type: string;
          code: string;
          name: string;
          head_employee_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parent_id?: string | null;
          unit_type?: string;
          code?: string;
          name?: string;
          head_employee_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pds_declaration_answers: {
        Row: {
          employee_id: string;
          question_code: string;
          answer: boolean;
          details: string | null;
          updated_at: string;
        };
        Insert: {
          employee_id: string;
          question_code: string;
          answer: boolean;
          details?: string | null;
          updated_at?: string;
        };
        Update: {
          employee_id?: string;
          question_code?: string;
          answer?: boolean;
          details?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      pds_declaration_questions: {
        Row: {
          code: string;
          label: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          code: string;
          label: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          label?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      pds_submissions: {
        Row: {
          id: string;
          employee_id: string;
          kind: string;
          by_user: string;
          by_name: string;
          remarks: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          kind: string;
          by_user?: string;
          by_name: string;
          remarks?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          kind?: string;
          by_user?: string;
          by_name?: string;
          remarks?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          code: string;
          module: string;
          description: string;
        };
        Insert: {
          code: string;
          module: string;
          description: string;
        };
        Update: {
          code?: string;
          module?: string;
          description?: string;
        };
        Relationships: [];
      };
      plantilla_items: {
        Row: {
          id: string;
          item_number: string;
          position_id: string;
          org_unit_id: string;
          salary_grade: number | null;
          is_active: boolean;
          remarks: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_number: string;
          position_id: string;
          org_unit_id: string;
          salary_grade?: number | null;
          is_active?: boolean;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          item_number?: string;
          position_id?: string;
          org_unit_id?: string;
          salary_grade?: number | null;
          is_active?: boolean;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      positions: {
        Row: {
          id: string;
          code: string;
          title: string;
          salary_grade: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          title: string;
          salary_grade?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          title?: string;
          salary_grade?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          user_id: string;
          employee_id: string | null;
          display_name: string;
          email: string | null;
          is_active: boolean;
          privacy_acknowledged_at: string | null;
          privacy_notice_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          employee_id?: string | null;
          display_name: string;
          email?: string | null;
          is_active?: boolean;
          privacy_acknowledged_at?: string | null;
          privacy_notice_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          employee_id?: string | null;
          display_name?: string;
          email?: string | null;
          is_active?: boolean;
          privacy_acknowledged_at?: string | null;
          privacy_notice_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_code: string;
        };
        Insert: {
          role_id: string;
          permission_code: string;
        };
        Update: {
          role_id?: string;
          permission_code?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          is_system: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      service_records: {
        Row: {
          id: string;
          employee_id: string;
          date_from: string;
          date_to: string | null;
          record_type: string;
          position_title: string;
          appointment_status: string | null;
          office: string | null;
          station: string | null;
          monthly_salary: number | null;
          salary_grade: number | null;
          salary_step: number | null;
          lwop_days: number;
          separation_cause: string | null;
          remarks: string | null;
          document_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          date_from: string;
          date_to?: string | null;
          record_type?: string;
          position_title: string;
          appointment_status?: string | null;
          office?: string | null;
          station?: string | null;
          monthly_salary?: number | null;
          salary_grade?: number | null;
          salary_step?: number | null;
          lwop_days?: number;
          separation_cause?: string | null;
          remarks?: string | null;
          document_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          date_from?: string;
          date_to?: string | null;
          record_type?: string;
          position_title?: string;
          appointment_status?: string | null;
          office?: string | null;
          station?: string | null;
          monthly_salary?: number | null;
          salary_grade?: number | null;
          salary_step?: number | null;
          lwop_days?: number;
          separation_cause?: string | null;
          remarks?: string | null;
          document_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      system_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          user_id: string;
          role_id: string;
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          role_id: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          role_id?: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Relationships: [];
      };
      workflow_actions: {
        Row: {
          id: number;
          entity_type: string;
          entity_id: string;
          step_order: number | null;
          step_name: string | null;
          action: string;
          actor_user_id: string | null;
          actor_name: string;
          remarks: string | null;
          from_status: string | null;
          to_status: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          entity_type: string;
          entity_id: string;
          step_order?: number | null;
          step_name?: string | null;
          action: string;
          actor_user_id?: string | null;
          actor_name: string;
          remarks?: string | null;
          from_status?: string | null;
          to_status?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          entity_type?: string;
          entity_id?: string;
          step_order?: number | null;
          step_name?: string | null;
          action?: string;
          actor_user_id?: string | null;
          actor_name?: string;
          remarks?: string | null;
          from_status?: string | null;
          to_status?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      workflow_steps: {
        Row: {
          id: string;
          workflow_code: string;
          step_order: number;
          name: string;
          actor_kind: string;
          required_permission: string | null;
          status_on_approve: string;
        };
        Insert: {
          id?: string;
          workflow_code: string;
          step_order: number;
          name: string;
          actor_kind: string;
          required_permission?: string | null;
          status_on_approve?: string;
        };
        Update: {
          id?: string;
          workflow_code?: string;
          step_order?: number;
          name?: string;
          actor_kind?: string;
          required_permission?: string | null;
          status_on_approve?: string;
        };
        Relationships: [];
      };
      workflows: {
        Row: {
          code: string;
          name: string;
          entity_type: string;
          description: string | null;
          is_default: boolean;
          is_active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          entity_type: string;
          description?: string | null;
          is_default?: boolean;
          is_active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          entity_type?: string;
          description?: string | null;
          is_default?: boolean;
          is_active?: boolean;
        };
        Relationships: [];
      };
    };
    Views: {
      current_service_record: {
        Row: {
          id: string | null;
          employee_id: string | null;
          date_from: string | null;
          date_to: string | null;
          record_type: string | null;
          position_title: string | null;
          appointment_status: string | null;
          office: string | null;
          station: string | null;
          monthly_salary: number | null;
          salary_grade: number | null;
          salary_step: number | null;
          lwop_days: number | null;
          separation_cause: string | null;
          remarks: string | null;
          document_id: string | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
      employee_directory: {
        Row: {
          id: string | null;
          employee_no: string | null;
          full_name: string | null;
          first_name: string | null;
          last_name: string | null;
          position_id: string | null;
          position_title: string | null;
          salary_grade: number | null;
          salary_step: number | null;
          employment_status_code: string | null;
          employment_status_name: string | null;
          org_unit_id: string | null;
          unit_name: string | null;
          division_id: string | null;
          division_name: string | null;
          supervisor_employee_id: string | null;
          record_status: string | null;
        };
        Relationships: [];
      };
      leave_balance_summary: {
        Row: {
          employee_id: string | null;
          leave_type_code: string | null;
          leave_type_name: string | null;
          year: number | null;
          beginning: number | null;
          earned: number | null;
          used: number | null;
          pending: number | null;
          available: number | null;
        };
        Relationships: [];
      };
      org_unit_ancestry: {
        Row: {
          unit_id: string | null;
          ancestor_id: string | null;
          depth: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      acknowledge_privacy: {
        Args: { p_version: string | null };
        Returns: undefined;
      };
      add_document_version: {
        Args: { p_document_id: string | null; p_storage_path: string | null; p_file_name: string | null; p_mime_type: string | null; p_size_bytes: number | null; p_sha256: string | null; p_reason: string | null };
        Returns: number;
      };
      admin_provision_user: {
        Args: { p_user_id: string | null; p_email: string | null; p_display_name: string | null; p_employee_id: string | null; p_role_codes: string[] | null };
        Returns: undefined;
      };
      admin_remaining_super_admins: {
        Args: { p_excluding: string | null };
        Returns: number;
      };
      admin_save_role: {
        Args: { p_role_id: string | null; p_code: string | null; p_name: string | null; p_description: string | null; p_permission_codes: string[] | null };
        Returns: string;
      };
      admin_set_user_active: {
        Args: { p_user: string | null; p_active: boolean | null };
        Returns: undefined;
      };
      admin_set_user_roles: {
        Args: { p_user: string | null; p_role_codes: string[] | null };
        Returns: undefined;
      };
      assert_report_access: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      assert_storage_object: {
        Args: { p_employee: string | null; p_path: string | null };
        Returns: undefined;
      };
      assignable_staff: {
        Args: Record<PropertyKey, never>;
        Returns: { user_id: string; display_name: string }[];
      };
      audit_actor_label: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      audit_request_metadata: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      can_read_document: {
        Args: { p_document: string | null };
        Returns: boolean;
      };
      can_read_employee: {
        Args: { p_employee: string | null };
        Returns: boolean;
      };
      can_read_request: {
        Args: { p_entity_type: string | null; p_id: string | null };
        Returns: boolean;
      };
      can_upload_document_for: {
        Args: { p_employee: string | null };
        Returns: boolean;
      };
      check_upload: {
        Args: { p_mime: string | null; p_size: number | null };
        Returns: undefined;
      };
      commit_employee_import: {
        Args: { p_batch: string | null };
        Returns: Json;
      };
      create_document: {
        Args: { p_employee_id: string | null; p_category_code: string | null; p_title: string | null; p_doc_date: string | null; p_issuing_agency: string | null; p_expires_on: string | null; p_remarks: string | null; p_related_type: string | null; p_related_id: string | null; p_storage_path: string | null; p_file_name: string | null; p_mime_type: string | null; p_size_bytes: number | null; p_sha256: string | null };
        Returns: string;
      };
      current_employee_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      dashboard_executive: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      dashboard_hr: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      data_quality_report: {
        Args: Record<PropertyKey, never>;
        Returns: { check_code: string; severity: string; employee_id: string; employee_no: string; full_name: string; detail: string }[];
      };
      delete_document: {
        Args: { p_document_id: string | null; p_reason: string | null };
        Returns: undefined;
      };
      employee_change_history: {
        Args: { p_employee: string | null };
        Returns: { occurred_at: string; changed_by: string; table_name: string; field: string; old_value: string; new_value: string; reason: string }[];
      };
      has_permission: {
        Args: { p_code: string | null };
        Returns: boolean;
      };
      has_role: {
        Args: { p_role_code: string | null };
        Returns: boolean;
      };
      headed_unit_ids: {
        Args: { p_employee: string | null };
        Returns: string[];
      };
      hr_request_assign: {
        Args: { p_request: string | null; p_user: string | null };
        Returns: undefined;
      };
      hr_request_attach_result: {
        Args: { p_request: string | null; p_document: string | null };
        Returns: undefined;
      };
      hr_save_employee: {
        Args: { p_employee_id: string | null; p_core: Json | null; p_private: Json | null; p_reason: string | null };
        Returns: string;
      };
      is_self: {
        Args: { p_employee: string | null };
        Returns: boolean;
      };
      log_event: {
        Args: { p_action: string | null; p_module: string | null; p_entity_type?: string | null; p_entity_id?: string | null; p_subject_employee_id?: string | null; p_metadata?: Json | null };
        Returns: undefined;
      };
      my_access: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      my_pending_actions: {
        Args: Record<PropertyKey, never>;
        Returns: { entity_type: string; entity_id: string; request_no: string; employee_id: string; employee_name: string; summary: string; step_name: string; submitted_at: string }[];
      };
      next_number: {
        Args: { p_prefix: string | null };
        Returns: string;
      };
      notify: {
        Args: { p_user_id: string | null; p_type: string | null; p_title: string | null; p_body?: string | null; p_link?: string | null; p_entity_type?: string | null; p_entity_id?: string | null };
        Returns: string;
      };
      pds_certify: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      pds_review: {
        Args: { p_employee: string | null; p_kind: string | null; p_remarks: string | null };
        Returns: string;
      };
      profile_completion: {
        Args: { p_employee: string | null };
        Returns: Json;
      };
      report_attendance_summary: {
        Args: { p_from: string | null; p_to: string | null; p_division?: string | null };
        Returns: { employee_no: string; full_name: string; division_name: string; present: number; late: number; undertime: number; absent: number; missing_log: number; on_leave: number; other: number; total_hours: number }[];
      };
      report_document_compliance: {
        Args: Record<PropertyKey, never>;
        Returns: { employee_no: string; full_name: string; division_name: string; category: string; compliance: string }[];
      };
      report_hr_requests: {
        Args: { p_from: string | null; p_to: string | null };
        Returns: { request_no: string; request_type: string; requester: string; priority: string; status: string; submitted_at: string; completed_at: string; days_open: number }[];
      };
      report_leave_summary: {
        Args: { p_year: number | null; p_division?: string | null };
        Returns: { employee_no: string; full_name: string; division_name: string; leave_type: string; beginning: number; earned: number; used: number; pending: number; available: number }[];
      };
      report_personnel_movement: {
        Args: { p_from: string | null; p_to: string | null };
        Returns: { employee_no: string; full_name: string; division_name: string; record_type: string; position_title: string; appointment_status: string; effective_date: string; remarks: string }[];
      };
      report_plantilla_summary: {
        Args: Record<PropertyKey, never>;
        Returns: { item_number: string; position_title: string; salary_grade: number; unit_name: string; incumbent: string; employment_status: string }[];
      };
      report_training_summary: {
        Args: { p_from: string | null; p_to: string | null };
        Returns: { employee_no: string; full_name: string; division_name: string; trainings: number; total_hours: number }[];
      };
      search_employees: {
        Args: { p_query?: string | null; p_division?: string | null; p_status?: string | null; p_record_status?: string | null; p_limit?: number | null; p_offset?: number | null };
        Returns: { id: string; employee_no: string; full_name: string; position_title: string; employment_status_name: string; division_name: string; unit_name: string; record_status: string; total_count: number }[];
      };
      set_document_status: {
        Args: { p_document_id: string | null; p_status: string | null; p_remarks: string | null };
        Returns: undefined;
      };
      setting_text: {
        Args: { p_key: string | null; p_default?: string | null };
        Returns: string;
      };
      supervises: {
        Args: { p_employee: string | null };
        Returns: boolean;
      };
      supervisor_user_ids: {
        Args: { p_employee: string | null };
        Returns: string[];
      };
      update_document_details: {
        Args: { p_document_id: string | null; p_title: string | null; p_doc_date: string | null; p_issuing_agency: string | null; p_expires_on: string | null; p_remarks: string | null };
        Returns: undefined;
      };
      update_my_contact: {
        Args: { p_personal_email: string | null; p_mobile_no: string | null };
        Returns: undefined;
      };
      users_with_permission: {
        Args: { p_code: string | null };
        Returns: string[];
      };
      wf_act: {
        Args: { p_type: string | null; p_id: string | null; p_action: string | null; p_remarks?: string | null };
        Returns: undefined;
      };
      wf_can_act: {
        Args: { p_step: unknown | null; p_employee: string | null };
        Returns: boolean;
      };
      wf_comment: {
        Args: { p_type: string | null; p_id: string | null; p_remarks: string | null };
        Returns: undefined;
      };
      wf_employee_of: {
        Args: { p_entity_type: string | null; p_id: string | null };
        Returns: string;
      };
      wf_link: {
        Args: { p_entity_type: string | null; p_id: string | null };
        Returns: string;
      };
      wf_log: {
        Args: { p_type: string | null; p_id: string | null; p_step_order: number | null; p_step_name: string | null; p_action: string | null; p_remarks: string | null; p_from: string | null; p_to: string | null };
        Returns: undefined;
      };
      wf_notify_step: {
        Args: { p_type: string | null; p_id: string | null; p_request_no: string | null; p_employee: string | null; p_step: unknown | null };
        Returns: undefined;
      };
      wf_read_all_permission: {
        Args: { p_entity_type: string | null };
        Returns: string;
      };
      wf_submit: {
        Args: { p_type: string | null; p_id: string | null };
        Returns: undefined;
      };
      wf_table: {
        Args: { p_entity_type: string | null };
        Returns: string;
      };
      wf_validate_submit: {
        Args: { p_type: string | null; p_id: string | null };
        Returns: undefined;
      };
      working_days: {
        Args: { p_from: string | null; p_to: string | null };
        Returns: number;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
